version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:16.6.0

jobs:
  install-dependencies:
    executor: main-executor
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  check-format:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn prettier:check

  build:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  build-and-deploy-docker-image:
    executor: main-executor
    parameters:
      app_name:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: ./
      - run:
          command: npx caprover deploy -h $HOST -p $PASSWORD -b master -a << parameters.app_name >>

workflows:
  version: 2

  deploy:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /.*/
      - check-format:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - build-and-deploy-docker-image:
          name: build-and-deploy-docker-image-staging
          app_name: voiturier-staging
          requires:
            - build
            - check-format
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - build-and-deploy-docker-image:
          app_name: voiturier
          requires:
            - build
            - check-format
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.+/
